service: securechain-finance

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:table/*'

functions:
  login:
    handler: functions/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  register:
    handler: functions/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  createTransaction:
    handler: functions/transactions/createTransaction.handler
    events:
      - http:
          path: transactions/create
          method: post
          cors: true

  getTransaction:
    handler: functions/transactions/getTransaction.handler
    events:
      - http:
          path: transactions/{transactionId}
          method: get
          cors: true

  updateUser:
    handler: functions/users/updateUser.handler
    events:
      - http:
          path: users/{userId}
          method: put
          cors: true

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TransactionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Transactions
        AttributeDefinitions:
          - AttributeName: transactionId
            AttributeType: S
        KeySchema:
          - AttributeName: transactionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
